### ISSUE TITLE
PAM module

### ISSUE THREAD

**Issue by MrM40** [CamW/npam#4]
Would it be usable to create your own PAM module?

**Comment by CamW** [comment]
Not sure that I understand your question. It is possible to create your own PAM module. An example of one I've created can be found here: https://github.com/CamW/pam-log-response

**Comment by MrM40** [comment]
I want to make my own PAM module (to use in my pam.d config file) for bruteforce mitigation. But it seem I cannot use neither napm or pam-log-response for this purpose, it seems it's only for implementing PAM support in you own .Net applications. But it was not clear to me after reading the readme.
But I'll try to play with [Pam-python](http://pam-python.sourceforge.net/), but I would prefer to use .net core.

**Comment by CamW** [comment]
npam could help with building a PAM module in .net core since it's the other side of the same interface but you would need to figure out registering the .net core module and getting the calls into your module. pam-log-response is an example of a pam module written in C.
