### ISSUE TITLE
Is it possible the assembly to be strong-name/signed?

### ISSUE THREAD

**Issue by georgiuk** [CamW/npam#9]

**Comment by CamW** [comment]
While looking into how to sign .net core assemblies, I found https://github.com/dotnet/docs/issues/22412 which relates to microsoft's assertion that strong-naming adds no benefit [here](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named) based on that github issue, it looks like they are getting rid of strong-naming. As a result of this, I have no reason to sign this assembly. In fact, I have a reason not to do it. Do you want to provide some justification for why you'd like it strong named?

**Comment by alexeyzimarev** [comment]
@CamW out of curiosity, what are the reasons that you have for not signing the assembly? I had the same dilemma before, and I ended up signing the assembly. From my perspective, the issue only comes when a signed assembly uses an unsigned assembly, as it might blow up. But, if your assembly has no references, or only uses signed assemblies, there's no real issue there.

Btw, .NET Core assemblies [all have strong names](https://github.com/dotnet/runtime/blob/202ccdb59afedcf2d7e86b3ba10a2b9a703c71c9/docs/project/strong-name-signing.md) now.

**Comment by CamW** [comment]
Reason not to: "For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding." from [here](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named). Are you using .NET Framework and not Core?

**Comment by alexeyzimarev** [comment]
I asked not because I use Noam but because I stumbled upon this issue from it being linked elsewhere. I just see that Npam targets .NET Standard, which makes it usable by .NET Framework-based software. I just shared my experience from a few years back when I decided to make the RestSharp assembly signed by default to avoid issues with references from signed assemblies on .NET FW.

**Comment by georgiuk** [comment]
Hi,
we are referring NPam from strong named assemblies in our ODOS framework (https://www.missionware.com/odos/). Because it is framework and comes from many years ago it can be used both in legacy and new .NET. That's why ODOS framework dlls are strong named. Currently we have to sign npam ourselves with a tool we have but it would be better if it was signed directly inside the nuget package.

**Comment by georgiuk** [comment]
We have signed the assembly and offer it here as nuget : https://www.nuget.org/packages/Missionware.ThirdParty.Npam
I can't find any reason not to sign such a package, even if typically is something from the past. 
In case it is signed from you we will gladly unlist it.
